/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PassportApplication = IDL.Record({
  'id' : IDL.Nat,
  'issueDate' : IDL.Text,
  'placeOfBirth' : IDL.Text,
  'status' : IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Text,
    'Pending' : IDL.Null,
  }),
  'owner' : IDL.Principal,
  'dateOfBirth' : IDL.Text,
  'expiryDate' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'nationality' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'passportNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApplicationStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'approvedCount' : IDL.Nat,
  'rejectedCount' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveApplication' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdmin' : IDL.Func([], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(PassportApplication)],
      ['query'],
    ),
  'getApplicationById' : IDL.Func([IDL.Nat], [PassportApplication], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Nat], [PassportApplication], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(PassportApplication)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getStats' : IDL.Func([], [ApplicationStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lookupByPassportNumber' : IDL.Func(
      [IDL.Text],
      [PassportApplication],
      ['query'],
    ),
  'rejectApplication' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegister' : IDL.Func([], [UserRole], []),
  'submitApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PassportApplication = IDL.Record({
    'id' : IDL.Nat,
    'issueDate' : IDL.Text,
    'placeOfBirth' : IDL.Text,
    'status' : IDL.Variant({
      'Approved' : IDL.Null,
      'Rejected' : IDL.Text,
      'Pending' : IDL.Null,
    }),
    'owner' : IDL.Principal,
    'dateOfBirth' : IDL.Text,
    'expiryDate' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'nationality' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'passportNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApplicationStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'approvedCount' : IDL.Nat,
    'rejectedCount' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveApplication' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdmin' : IDL.Func([], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(PassportApplication)],
        ['query'],
      ),
    'getApplicationById' : IDL.Func(
        [IDL.Nat],
        [PassportApplication],
        ['query'],
      ),
    'getApplicationStatus' : IDL.Func([IDL.Nat], [PassportApplication], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyApplications' : IDL.Func(
        [],
        [IDL.Vec(PassportApplication)],
        ['query'],
      ),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getStats' : IDL.Func([], [ApplicationStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lookupByPassportNumber' : IDL.Func(
        [IDL.Text],
        [PassportApplication],
        ['query'],
      ),
    'rejectApplication' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegister' : IDL.Func([], [UserRole], []),
    'submitApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };