/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplicationStats {
  'pendingCount' : bigint,
  'approvedCount' : bigint,
  'rejectedCount' : bigint,
  'totalApplications' : bigint,
}
export interface PassportApplication {
  'id' : bigint,
  'issueDate' : string,
  'placeOfBirth' : string,
  'status' : { 'Approved' : null } |
    { 'Rejected' : string } |
    { 'Pending' : null },
  'owner' : Principal,
  'dateOfBirth' : string,
  'expiryDate' : string,
  'fullName' : string,
  'submittedAt' : bigint,
  'nationality' : string,
  'address' : string,
  'gender' : string,
  'passportNumber' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveApplication' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], undefined>,
  'getAllApplications' : ActorMethod<[], Array<PassportApplication>>,
  'getApplicationById' : ActorMethod<[bigint], PassportApplication>,
  'getApplicationStatus' : ActorMethod<[bigint], PassportApplication>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyApplications' : ActorMethod<[], Array<PassportApplication>>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getStats' : ActorMethod<[], ApplicationStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lookupByPassportNumber' : ActorMethod<[string], PassportApplication>,
  'rejectApplication' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[], UserRole>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];